package com.kenan.optishare;

import android.Manifest;
import android.app.AlertDialog;
import android.content.*;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.location.LocationManager;
import android.net.*;
import android.net.wifi.WpsInfo;
import android.net.wifi.p2p.*;
import android.os.*;
import android.provider.MediaStore;
import android.provider.OpenableColumns;
import android.provider.Settings;
import android.view.*;
import android.widget.*;

import androidx.activity.ComponentActivity;
import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.core.content.ContextCompat;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.common.BitMatrix;
import com.journeyapps.barcodescanner.ScanContract;
import com.journeyapps.barcodescanner.ScanOptions;

import java.io.*;
import java.net.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.*;

public class ShareActivity extends ComponentActivity implements WifiP2pManager.PeerListListener, WifiP2pManager.ConnectionInfoListener {
    private static final int PORT=8988, MAGIC=0x4F503039, HOME=0, SEND=1, RECEIVE=2, REQ=909;
    private final ExecutorService io=Executors.newCachedThreadPool();
    private final List<WifiP2pDevice> peers=new ArrayList<>();
    private final List<Uri> files=new ArrayList<>();
    private final Handler handler=new Handler();
    private WifiP2pManager mgr; private WifiP2pManager.Channel ch; private WifiP2pDevice me;
    private int mode=HOME; private String targetAddr,targetName,token;
    private Socket sock; private DataInputStream in; private DataOutputStream out; private boolean socketStarting,receiverLoop;
    private LinearLayout screen,peerList; private TextView stateTitle,stateSub,transferTitle,transferSub,pathText; private View dot; private ProgressBar bar;

    private final Runnable scanLoop=new Runnable(){public void run(){if(mode!=SEND)return;discover(false);handler.postDelayed(this,2500);}};

    private final ActivityResultLauncher<String[]> picker=registerForActivityResult(new ActivityResultContracts.OpenMultipleDocuments(), uris->{
        if(uris==null||uris.isEmpty())return; files.clear(); files.addAll(uris); mode=SEND; showSend(); startScanLoop();
    });
    private final ActivityResultLauncher<ScanOptions> scanner=registerForActivityResult(new ScanContract(), r->{if(r!=null&&r.getContents()!=null)handleQr(r.getContents());});

    private final BroadcastReceiver receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){String a=i.getAction();
        if(WifiP2pManager.WIFI_P2P_THIS_DEVICE_CHANGED_ACTION.equals(a)){me=i.getParcelableExtra(WifiP2pManager.EXTRA_WIFI_P2P_DEVICE);if(mode==RECEIVE)updateQr();}
        else if(WifiP2pManager.WIFI_P2P_PEERS_CHANGED_ACTION.equals(a)){if(hasPerm())try{mgr.requestPeers(ch,ShareActivity.this);}catch(SecurityException e){blocked(e);}}
        else if(WifiP2pManager.WIFI_P2P_CONNECTION_CHANGED_ACTION.equals(a)){NetworkInfo n=i.getParcelableExtra(WifiP2pManager.EXTRA_NETWORK_INFO);if(n!=null&&n.isConnected()){status("Connected","Opening private transfer channel…",2);try{mgr.requestConnectionInfo(ch,ShareActivity.this);}catch(SecurityException e){blocked(e);}}else if(mode==SEND)status("Searching","Looking for a receiver",1);else if(mode==RECEIVE)status("Ready to receive","Waiting for a sender",1);}
        else if(WifiP2pManager.WIFI_P2P_STATE_CHANGED_ACTION.equals(a)&&i.getIntExtra(WifiP2pManager.EXTRA_WIFI_STATE,-1)!=WifiP2pManager.WIFI_P2P_STATE_ENABLED)status("Wi‑Fi is off","Turn on Wi‑Fi to continue",3);
    }};

    @Override protected void onCreate(Bundle b){super.onCreate(b);mgr=(WifiP2pManager)getSystemService(WIFI_P2P_SERVICE);if(mgr!=null)ch=mgr.initialize(this,getMainLooper(),()->status("Connection service restarted","Reopen OptiShare if needed",3));build();askPerm();home();}

    private void build(){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(18),dp(20),dp(24));root.setBackground(gradient(0xFF07101F,0xFF0B1D34,0));sv.addView(root);
        LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);TextView logo=t("O",22,Color.WHITE,true);logo.setGravity(Gravity.CENTER);logo.setBackground(round(0xFF2AA6FF,18));brand.addView(logo,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout bt=new LinearLayout(this);bt.setOrientation(LinearLayout.VERTICAL);bt.setPadding(dp(12),0,0,0);bt.addView(t("OptiShare",27,Color.WHITE,true));bt.addView(t("Fast local sharing",12,0xFF95BBD7,false));brand.addView(bt,new LinearLayout.LayoutParams(0,-2,1));root.addView(brand);
        LinearLayout sc=card(0xFF0F2237);LinearLayout sr=new LinearLayout(this);sr.setGravity(Gravity.CENTER_VERTICAL);dot=new View(this);LinearLayout.LayoutParams dl=new LinearLayout.LayoutParams(dp(11),dp(11));dl.setMargins(0,0,dp(10),0);sr.addView(dot,dl);LinearLayout texts=new LinearLayout(this);texts.setOrientation(LinearLayout.VERTICAL);stateTitle=t("Ready",16,Color.WHITE,true);stateSub=t("Choose Send or Receive",12,0xFF96B0C7,false);texts.addView(stateTitle);texts.addView(stateSub);sr.addView(texts,new LinearLayout.LayoutParams(0,-2,1));sc.addView(sr);LinearLayout.LayoutParams scl=new LinearLayout.LayoutParams(-1,-2);scl.setMargins(0,dp(18),0,0);root.addView(sc,scl);
        screen=new LinearLayout(this);screen.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams sl=new LinearLayout.LayoutParams(-1,-2);sl.setMargins(0,dp(16),0,0);root.addView(screen,sl);
        LinearLayout tc=card(0xFF0C1B2D);transferTitle=t("No active transfer",15,Color.WHITE,true);transferSub=t("Speed and progress will appear here.",12,0xFF8DA6BE,false);bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(1000);tc.addView(transferTitle);tc.addView(transferSub);LinearLayout.LayoutParams bl=new LinearLayout.LayoutParams(-1,dp(7));bl.setMargins(0,dp(10),0,0);tc.addView(bar,bl);LinearLayout.LayoutParams tcl=new LinearLayout.LayoutParams(-1,-2);tcl.setMargins(0,dp(16),0,0);root.addView(tc,tcl);
        pathText=t("Received files → Internal storage/Download/OptiShare",12,0xFF67CAFF,false);pathText.setPadding(0,dp(14),0,0);root.addView(pathText);TextView foot=t("No Internet required  •  Designed & developed by Kenan Alhennawi",11,0xFF6B96B5,false);foot.setGravity(Gravity.CENTER);foot.setPadding(0,dp(20),0,0);root.addView(foot);setContentView(sv);}

    private void home(){stopScan();mode=HOME;files.clear();targetAddr=targetName=token=null;closeSock();removeGroup();screen.removeAllViews();screen.addView(t("Share anything nearby",24,Color.WHITE,true));TextView sub=t("Choose a role. OptiShare handles discovery and pairing.",13,0xFF9AB5CD,false);sub.setPadding(0,dp(4),0,dp(16));screen.addView(sub);
        LinearLayout row=new LinearLayout(this);Button send=action("↑","Send","Files & media",0xFF30A4FF,0xFF175B9A);send.setOnClickListener(v->picker.launch(new String[]{"*/*"}));Button recv=action("↓","Receive","From nearby",0xFF5ED093,0xFF207248);recv.setOnClickListener(v->receive());row.addView(send,new LinearLayout.LayoutParams(0,dp(152),1));LinearLayout.LayoutParams rlp=new LinearLayout.LayoutParams(0,dp(152),1);rlp.setMargins(dp(10),0,0,0);row.addView(recv,rlp);screen.addView(row);
        LinearLayout info=card(0xFF0D1F32);info.addView(t("Received files",15,Color.WHITE,true));info.addView(t("Saved to Download/OptiShare — visible from your normal Files app.",12,0xFF91ABC2,false));LinearLayout br=new LinearLayout(this);Button open=secondary("Open Downloads");open.setOnClickListener(v->openDownloads());Button where=secondary("Where are my files?");where.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Received files").setMessage("Internal storage\n→ Download\n→ OptiShare").setPositiveButton("Open Downloads",(d,w)->openDownloads()).setNegativeButton("Close",null).show());br.addView(open,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams wl=new LinearLayout.LayoutParams(0,dp(48),1);wl.setMargins(dp(8),0,0,0);br.addView(where,wl);LinearLayout.LayoutParams brr=new LinearLayout.LayoutParams(-1,-2);brr.setMargins(0,dp(12),0,0);info.addView(br,brr);LinearLayout.LayoutParams il=new LinearLayout.LayoutParams(-1,-2);il.setMargins(0,dp(12),0,0);screen.addView(info,il);status("Ready","Choose Send or Receive",0);resetTransfer();}

    private void showSend(){screen.removeAllViews();screen.addView(t("Send",23,Color.WHITE,true));long total=0;for(Uri u:files){long s=size(u);if(s>0)total+=s;}TextView s=t(files.size()+" selected • "+bytes(total),13,0xFF97B8D1,false);s.setPadding(0,dp(3),0,dp(10));screen.addView(s);LinearLayout selected=card(0xFF0E2237);int n=Math.min(4,files.size());for(int i=0;i<n;i++){Uri u=files.get(i);selected.addView(fileRow(name(u),size(u)));}if(files.size()>n)selected.addView(t("+ "+(files.size()-n)+" more files",12,0xFF6EC8FF,true));screen.addView(selected);
        LinearLayout hdr=new LinearLayout(this);hdr.setGravity(Gravity.CENTER_VERTICAL);hdr.addView(t("Nearby receivers",16,Color.WHITE,true),new LinearLayout.LayoutParams(0,-2,1));Button qr=tiny("Scan QR");qr.setOnClickListener(v->scanQr());hdr.addView(qr,new LinearLayout.LayoutParams(dp(108),dp(42)));LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,-2);hp.setMargins(0,dp(16),0,dp(8));screen.addView(hdr,hp);RadarView radar=new RadarView(this);screen.addView(radar,new LinearLayout.LayoutParams(-1,dp(170)));peerList=new LinearLayout(this);peerList.setOrientation(LinearLayout.VERTICAL);screen.addView(peerList);placeholder();status("Searching","Looking for receiving phones nearby",1);}

    private void receive(){if(!prereq(true))return;mode=RECEIVE;token=UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.US);screen.removeAllViews();TextView title=t("Ready to receive",23,Color.WHITE,true);title.setGravity(Gravity.CENTER);screen.addView(title);TextView sub=t("Keep this screen open. Senders can find you automatically or scan your QR.",13,0xFF97B8D1,false);sub.setGravity(Gravity.CENTER);sub.setPadding(dp(12),dp(4),dp(12),dp(14));screen.addView(sub);screen.addView(new RadarView(this),new LinearLayout.LayoutParams(-1,dp(150)));TextView w=t("Creating receiving session…",14,0xFF67CAFF,true);w.setGravity(Gravity.CENTER);w.setTag("wait");screen.addView(w);Button stop=secondary("Stop receiving");stop.setOnClickListener(v->home());LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(48));sp.setMargins(0,dp(14),0,0);screen.addView(stop,sp);status("Starting receiver","Preparing direct connection",1);
        try{mgr.createGroup(ch,new WifiP2pManager.ActionListener(){public void onSuccess(){status("Ready to receive","Waiting for sender",1);try{mgr.requestDeviceInfo(ch,d->{me=d;updateQr();});}catch(SecurityException e){blocked(e);}}public void onFailure(int r){p2pFail("Could not start receiver",r);}});}catch(SecurityException e){blocked(e);}}

    private void updateQr(){if(mode!=RECEIVE||me==null||me.deviceAddress==null)return;runOnUiThread(()->{TextView wait=screen.findViewWithTag("wait");if(wait!=null)wait.setText("Visible as "+deviceName(me));View old=screen.findViewWithTag("qr");if(old!=null)screen.removeView(old);try{ImageView q=new ImageView(this);q.setTag("qr");q.setImageBitmap(makeQr("OPTISHARE9|"+token+"|"+me.deviceAddress+"|"+deviceName(me),720));q.setAdjustViewBounds(true);q.setPadding(dp(12),dp(12),dp(12),dp(12));q.setBackground(round(Color.WHITE,18));LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(-1,dp(280));qp.setMargins(0,dp(12),0,0);screen.addView(q,Math.max(0,screen.getChildCount()-1),qp);}catch(Exception ignored){}});}

    private void startScan(){stopScan();handler.post(scanLoop);}private void stopScan(){handler.removeCallbacks(scanLoop);}private void discover(boolean user){if(mode!=SEND||!prereq(user))return;try{mgr.discoverPeers(ch,new WifiP2pManager.ActionListener(){public void onSuccess(){status("Searching","Scanning nearby receivers",1);try{mgr.requestPeers(ch,ShareActivity.this);}catch(SecurityException e){blocked(e);}}public void onFailure(int r){if(user||r!=WifiP2pManager.BUSY)p2pFail("Search failed",r);}});}catch(SecurityException e){blocked(e);}}

    @Override public void onPeersAvailable(WifiP2pDeviceList l){peers.clear();peers.addAll(l.getDeviceList());if(mode!=SEND)return;WifiP2pDevice match=null;if(targetAddr!=null){for(WifiP2pDevice d:peers)if(targetAddr.equalsIgnoreCase(d.deviceAddress)){match=d;break;}if(match==null&&targetName!=null)for(WifiP2pDevice d:peers)if(targetName.equalsIgnoreCase(deviceName(d))){match=d;break;}}if(match!=null){targetAddr=null;connect(match);return;}renderPeers();}

    private void renderPeers(){runOnUiThread(()->{if(peerList==null)return;peerList.removeAllViews();for(WifiP2pDevice d:peers){if(d.status==WifiP2pDevice.UNAVAILABLE)continue;LinearLayout c=card(0xFF0D1F32);LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView av=t(deviceName(d).substring(0,1).toUpperCase(Locale.US),17,Color.WHITE,true);av.setGravity(Gravity.CENTER);av.setBackground(round(0xFF2484CF,16));r.addView(av,new LinearLayout.LayoutParams(dp(46),dp(46)));LinearLayout labels=new LinearLayout(this);labels.setOrientation(LinearLayout.VERTICAL);labels.setPadding(dp(12),0,0,0);labels.addView(t(deviceName(d),15,Color.WHITE,true));labels.addView(t(deviceStatus(d.status),12,0xFF8CAAC3,false));r.addView(labels,new LinearLayout.LayoutParams(0,-2,1));Button b=tiny("Send here");b.setOnClickListener(v->connect(d));r.addView(b,new LinearLayout.LayoutParams(dp(110),dp(44)));c.addView(r);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(8));peerList.addView(c,cp);}if(peerList.getChildCount()==0)placeholder();});}

    private void placeholder(){if(peerList==null)return;peerList.removeAllViews();LinearLayout c=card(0xFF0C1C2E);TextView a=t("Searching automatically…",14,Color.WHITE,true);a.setGravity(Gravity.CENTER);c.addView(a);TextView b=t("Open Receive on the other phone. It should appear here automatically.",12,0xFF8DA9C1,false);b.setGravity(Gravity.CENTER);b.setPadding(dp(8),dp(4),dp(8),0);c.addView(b);peerList.addView(c);}

    private void connect(WifiP2pDevice d){stopScan();WifiP2pConfig cfg=new WifiP2pConfig();cfg.deviceAddress=d.deviceAddress;cfg.groupOwnerIntent=0;cfg.wps.setup=WpsInfo.PBC;status("Connecting",deviceName(d),1);try{mgr.connect(ch,cfg,new WifiP2pManager.ActionListener(){public void onSuccess(){status("Connection request sent","Waiting for Android to establish the link",1);}public void onFailure(int r){p2pFail("Connection failed",r);startScan();}});}catch(SecurityException e){blocked(e);startScan();}}

    @Override public void onConnectionInfoAvailable(WifiP2pInfo info){if(!info.groupFormed||info.groupOwnerAddress==null)return;status("Direct link established",(info.isGroupOwner?"Receiver":"Sender")+" • opening transfer channel",2);if(info.isGroupOwner)server();else client(info.groupOwnerAddress.getHostAddress());}
    private void server(){if(socketStarting||ready())return;socketStarting=true;io.execute(()->{try(ServerSocket ss=new ServerSocket(PORT)){ss.setReuseAddress(true);install(ss.accept());}catch(Exception e){status("Transfer channel error",safe(e),3);}finally{socketStarting=false;}});}private void client(String host){if(socketStarting||ready())return;socketStarting=true;io.execute(()->{try{Thread.sleep(300);Socket s=new Socket();s.connect(new InetSocketAddress(host,PORT),10000);install(s);}catch(Exception e){status("Transfer channel error",safe(e),3);}finally{socketStarting=false;}});}
    private synchronized void install(Socket s)throws Exception{closeSock();sock=s;sock.setTcpNoDelay(true);sock.setKeepAlive(true);in=new DataInputStream(new BufferedInputStream(sock.getInputStream(),262144));out=new DataOutputStream(new BufferedOutputStream(sock.getOutputStream(),262144));status("Connected ✓","Private transfer channel ready",2);if(mode==SEND&&!files.isEmpty())io.execute(this::sendBatch);else if(mode==RECEIVE&&!receiverLoop){receiverLoop=true;io.execute(this::receiveLoop);}}

    private void sendBatch(){try{List<Meta> ms=new ArrayList<>();long total=0;for(Uri u:files){long sz=size(u);if(sz<0)sz=measure(u);MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] buf=new byte[524288];try(InputStream x=getContentResolver().openInputStream(u)){int n;while((n=x.read(buf))!=-1)md.update(buf,0,n);}ms.add(new Meta(name(u),sz,md.digest()));total+=sz;}final long batch=total;runOnUiThread(()->{transferTitle.setText("Preparing "+ms.size()+" files");transferSub.setText(bytes(batch));bar.setProgress(0);});synchronized(this){out.writeInt(MAGIC);out.writeInt(ms.size());for(Meta m:ms){out.writeUTF(m.name);out.writeLong(m.size);out.writeInt(m.hash.length);out.write(m.hash);}out.flush();if(!in.readBoolean()){runOnUiThread(()->{transferTitle.setText("Transfer declined");transferSub.setText("The receiver declined this batch.");});return;}long done=0,start=System.nanoTime();byte[] buf=new byte[524288];for(int i=0;i<files.size();i++){try(InputStream raw=getContentResolver().openInputStream(files.get(i));BufferedInputStream x=new BufferedInputStream(raw,524288)){int n;while((n=x.read(buf))!=-1){out.write(buf,0,n);done+=n;updateProgress("Sending "+(i+1)+"/"+files.size(),ms.get(i).name,done,batch,start);}}}out.flush();}runOnUiThread(()->{transferTitle.setText("Sent ✓");transferSub.setText(ms.size()+" files • "+bytes(batch));bar.setProgress(1000);});}catch(Exception e){runOnUiThread(()->{transferTitle.setText("Send failed");transferSub.setText(safe(e));});}}

    private void receiveLoop(){try{while(sock!=null&&!sock.isClosed()){int magic;try{magic=in.readInt();}catch(EOFException e){break;}if(magic!=MAGIC)throw new IOException("Invalid OptiShare stream");int count=in.readInt();if(count<1||count>1000)throw new IOException("Invalid file count");List<Meta> ms=new ArrayList<>();long total=0;for(int i=0;i<count;i++){String n=sanitize(in.readUTF());long sz=in.readLong();int hl=in.readInt();if(sz<0||hl<16||hl>128)throw new IOException("Invalid metadata");byte[] h=new byte[hl];in.readFully(h);ms.add(new Meta(n,sz,h));total+=sz;}boolean accept=ask(ms,total);out.writeBoolean(accept);out.flush();if(!accept)continue;long done=0,start=System.nanoTime();for(int i=0;i<ms.size();i++){Meta m=ms.get(i);MessageDigest md=MessageDigest.getInstance("SHA-256");Save save=openSave(m.name);byte[] buf=new byte[524288];long remain=m.size;try(OutputStream fo=new BufferedOutputStream(save.out,524288)){while(remain>0){int want=(int)Math.min(buf.length,remain);int n=in.read(buf,0,want);if(n<0)throw new EOFException("Connection ended during transfer");fo.write(buf,0,n);md.update(buf,0,n);remain-=n;done+=n;updateProgress("Receiving "+(i+1)+"/"+ms.size(),m.name,done,total,start);}fo.flush();}if(!Arrays.equals(m.hash,md.digest())){delete(save);throw new IOException("Verification failed for "+m.name);}finish(save);}final long bytesDone=total;runOnUiThread(()->{transferTitle.setText("Received ✓");transferSub.setText(ms.size()+" files • "+bytes(bytesDone)+" • Download/OptiShare");bar.setProgress(1000);pathText.setText("Received files → Internal storage/Download/OptiShare ✓");});}}catch(Exception e){if(sock!=null&&!sock.isClosed())runOnUiThread(()->{transferTitle.setText("Transfer interrupted");transferSub.setText(safe(e));});}finally{receiverLoop=false;}}

    private boolean ask(List<Meta> ms,long total)throws InterruptedException{final Object lock=new Object();final boolean[] answer={false},done={false};runOnUiThread(()->{StringBuilder m=new StringBuilder(ms.size()+" files • "+bytes(total)+"\n\n");for(int i=0;i<Math.min(5,ms.size());i++)m.append("• ").append(ms.get(i).name).append("\n");if(ms.size()>5)m.append("• +").append(ms.size()-5).append(" more");new AlertDialog.Builder(this).setTitle("Incoming files").setMessage(m.toString()).setPositiveButton("Accept",(d,w)->{synchronized(lock){answer[0]=true;done[0]=true;lock.notifyAll();}}).setNegativeButton("Decline",(d,w)->{synchronized(lock){done[0]=true;lock.notifyAll();}}).setOnCancelListener(d->{synchronized(lock){done[0]=true;lock.notifyAll();}}).show();});synchronized(lock){while(!done[0])lock.wait();}return answer[0];}

    private void updateProgress(String phase,String file,long done,long total,long start){double sec=Math.max(.001,(System.nanoTime()-start)/1e9);double speed=(done/1048576.0)/sec;int p=total<=0?0:(int)Math.min(1000,done*1000L/total);runOnUiThread(()->{transferTitle.setText(phase+" • "+file);transferSub.setText(String.format(Locale.US,"%s / %s  •  %.2f MB/s  •  %d%%",bytes(done),bytes(total),speed,p/10));bar.setProgress(p);});}

    private void scanQr(){ScanOptions o=new ScanOptions();o.setPrompt("Scan the receiver's OptiShare QR");o.setBeepEnabled(false);o.setOrientationLocked(false);o.setDesiredBarcodeFormats(ScanOptions.QR_CODE);scanner.launch(o);}private void handleQr(String raw){if(mode!=SEND||files.isEmpty()){message("Select files first","Tap Send, select files, then scan the receiver QR.");return;}if(raw==null||!raw.startsWith("OPTISHARE9|")){message("Invalid QR","This is not an OptiShare receiver QR.");return;}String[] p=raw.split("\\|",4);if(p.length<4){message("Invalid QR","Pairing information is incomplete.");return;}targetAddr=p[2];targetName=p[3];status("Receiver identified",targetName+" • connecting automatically",1);discover(true);}

    private boolean prereq(boolean ui){if(mgr==null||ch==null){if(ui)message("Wi‑Fi Direct unavailable","This phone does not expose Wi‑Fi Direct to OptiShare.");return false;}if(!hasPerm()){askPerm();return false;}if(Build.VERSION.SDK_INT<=32&&!locationOn()){if(ui)new AlertDialog.Builder(this).setTitle("Turn on Location").setMessage("Android requires Location services for nearby Wi‑Fi Direct discovery on this version. No location data is sent.").setPositiveButton("Open settings",(d,w)->startActivity(new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS))).setNegativeButton("Cancel",null).show();return false;}return true;}
    private boolean hasPerm(){if(Build.VERSION.SDK_INT>=33)return checkSelfPermission(Manifest.permission.NEARBY_WIFI_DEVICES)==PackageManager.PERMISSION_GRANTED;return checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED;}private void askPerm(){if(hasPerm())return;if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.NEARBY_WIFI_DEVICES},REQ);else requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},REQ);}private boolean locationOn(){LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);if(lm==null)return false;if(Build.VERSION.SDK_INT>=28)return lm.isLocationEnabled();try{return lm.isProviderEnabled(LocationManager.GPS_PROVIDER)||lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER);}catch(Exception e){return false;}}
    private void blocked(Throwable e){runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Nearby connection blocked").setMessage("Android blocked Wi‑Fi Direct ("+safe(e)+").\n\nCheck:\n• Wi‑Fi is ON\n• Nearby devices permission is allowed\n"+(Build.VERSION.SDK_INT<=32?"• Location services are ON\n":"")+"Then return and retry.").setPositiveButton("App settings",(d,w)->{Intent x=new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);x.setData(Uri.parse("package:"+getPackageName()));startActivity(x);}).setNegativeButton("Close",null).show());}
    private void p2pFail(String title,int r){String s=r==WifiP2pManager.BUSY?"Wi‑Fi Direct is busy. Wait a moment and retry.":r==WifiP2pManager.P2P_UNSUPPORTED?"Wi‑Fi Direct is not supported by this device.":"Android Wi‑Fi Direct error "+r+". Check Wi‑Fi and nearby permissions.";status(title,s,3);}private void status(String title,String sub,int st){runOnUiThread(()->{if(stateTitle==null)return;stateTitle.setText(title);stateSub.setText(sub);int c=st==2?0xFF3FDC8F:st==1?0xFFFFC146:st==3?0xFFFF5B65:0xFF758FA7;dot.setBackground(round(c,30));});}

    private LinearLayout fileRow(String n,long s){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(5),0,dp(5));TextView i=t("F",13,Color.WHITE,true);i.setGravity(Gravity.CENTER);i.setBackground(round(0xFF2E80C0,12));r.addView(i,new LinearLayout.LayoutParams(dp(36),dp(36)));LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,0,0);l.addView(t(n,13,Color.WHITE,true));l.addView(t(s>=0?bytes(s):"Unknown size",11,0xFF89A4BC,false));r.addView(l,new LinearLayout.LayoutParams(0,-2,1));return r;}private LinearLayout card(int c){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(16),dp(16),dp(16));GradientDrawable g=round(c,18);g.setStroke(dp(1),0xFF1C364E);l.setBackground(g);return l;}private Button action(String icon,String title,String sub,int a,int b){Button x=new Button(this);x.setAllCaps(false);x.setGravity(Gravity.CENTER);x.setText(icon+"\n"+title+"\n"+sub);x.setTextColor(Color.WHITE);x.setTextSize(15);x.setTypeface(Typeface.DEFAULT_BOLD);x.setBackground(gradient(a,b,18));return x;}private Button secondary(String s){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(13);b.setBackground(round(0xFF183147,14));return b;}private Button tiny(String s){Button b=secondary(s);b.setPadding(dp(8),0,dp(8),0);return b;}private TextView t(String s,int z,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private GradientDrawable gradient(int a,int b,int r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{a,b});g.setCornerRadius(dp(r));return g;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}

    private String deviceName(WifiP2pDevice d){return d==null||d.deviceName==null||d.deviceName.trim().isEmpty()?"Android device":d.deviceName.trim();}private String deviceStatus(int s){switch(s){case WifiP2pDevice.CONNECTED:return"Connected";case WifiP2pDevice.INVITED:return"Connecting…";case WifiP2pDevice.AVAILABLE:return"Ready to receive";case WifiP2pDevice.UNAVAILABLE:return"Busy";default:return"Nearby";}}private String name(Uri u){Cursor c=null;try{c=getContentResolver().query(u,null,null,null,null);if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0){String n=c.getString(i);if(n!=null&&!n.isEmpty())return sanitize(n);}}}finally{if(c!=null)c.close();}return"file.bin";}private long size(Uri u){Cursor c=null;try{c=getContentResolver().query(u,null,null,null,null);if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.SIZE);if(i>=0&&!c.isNull(i))return c.getLong(i);}}finally{if(c!=null)c.close();}return-1;}private long measure(Uri u)throws Exception{long total=0;byte[] b=new byte[262144];try(InputStream x=getContentResolver().openInputStream(u)){int n;while((n=x.read(b))!=-1)total+=n;}return total;}private String sanitize(String s){return s.replace("/","_").replace("\\","_").replace("\u0000","_");}private String bytes(long b){if(b<1024)return b+" B";if(b<1048576)return String.format(Locale.US,"%.1f KB",b/1024.0);if(b<1073741824L)return String.format(Locale.US,"%.2f MB",b/1048576.0);return String.format(Locale.US,"%.2f GB",b/1073741824.0);}private String safe(Throwable e){String m=e==null?null:e.getMessage();return m==null||m.trim().isEmpty()?(e==null?"Unknown error":e.getClass().getSimpleName()):m;}

    private Save openSave(String name)throws Exception{if(Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,name);v.put(MediaStore.Downloads.MIME_TYPE,"application/octet-stream");v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/OptiShare");v.put(MediaStore.Downloads.IS_PENDING,1);Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null)throw new IOException("Could not create Downloads entry");OutputStream o=getContentResolver().openOutputStream(u);if(o==null)throw new IOException("Could not open Downloads file");return new Save(u,null,o);}File dir=new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),"OptiShare");if(!dir.exists()&&!dir.mkdirs())throw new IOException("Could not create Download/OptiShare");File f=new File(dir,name);if(f.exists())f=new File(dir,System.currentTimeMillis()+"-"+name);return new Save(null,f,new FileOutputStream(f));}private void finish(Save s){if(Build.VERSION.SDK_INT>=29&&s.uri!=null){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.IS_PENDING,0);getContentResolver().update(s.uri,v,null,null);}}private void delete(Save s){try{if(s.uri!=null)getContentResolver().delete(s.uri,null,null);else if(s.file!=null)s.file.delete();}catch(Exception ignored){}}
    private void openDownloads(){try{Intent i=new Intent(Intent.ACTION_VIEW);i.setData(Uri.parse("content://com.android.providers.downloads.documents/root/downloads"));startActivity(i);}catch(Exception e){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivity(i);}}private void message(String t,String m){runOnUiThread(()->new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("OK",null).show());}private Bitmap makeQr(String v,int s)throws Exception{BitMatrix m=new MultiFormatWriter().encode(v,BarcodeFormat.QR_CODE,s,s);Bitmap b=Bitmap.createBitmap(s,s,Bitmap.Config.RGB_565);for(int y=0;y<s;y++)for(int x=0;x<s;x++)b.setPixel(x,y,m.get(x,y)?Color.BLACK:Color.WHITE);return b;}
    private boolean ready(){return sock!=null&&sock.isConnected()&&!sock.isClosed()&&in!=null&&out!=null;}private synchronized void closeSock(){try{if(in!=null)in.close();}catch(Exception ignored){}try{if(out!=null)out.close();}catch(Exception ignored){}try{if(sock!=null)sock.close();}catch(Exception ignored){}in=null;out=null;sock=null;socketStarting=false;receiverLoop=false;}private void removeGroup(){if(mgr==null||ch==null||!hasPerm())return;try{mgr.removeGroup(ch,new WifiP2pManager.ActionListener(){public void onSuccess(){}public void onFailure(int r){}});}catch(Exception ignored){}}private void resetTransfer(){transferTitle.setText("No active transfer");transferSub.setText("Speed and progress will appear here.");bar.setProgress(0);}

    @Override protected void onResume(){super.onResume();IntentFilter f=new IntentFilter();f.addAction(WifiP2pManager.WIFI_P2P_STATE_CHANGED_ACTION);f.addAction(WifiP2pManager.WIFI_P2P_PEERS_CHANGED_ACTION);f.addAction(WifiP2pManager.WIFI_P2P_CONNECTION_CHANGED_ACTION);f.addAction(WifiP2pManager.WIFI_P2P_THIS_DEVICE_CHANGED_ACTION);ContextCompat.registerReceiver(this,receiver,f,ContextCompat.RECEIVER_NOT_EXPORTED);}@Override protected void onPause(){super.onPause();try{unregisterReceiver(receiver);}catch(Exception ignored){}}@Override protected void onDestroy(){stopScan();closeSock();io.shutdownNow();super.onDestroy();}@Override public void onBackPressed(){if(mode==HOME)super.onBackPressed();else home();}
    private static final class Meta{final String name;final long size;final byte[] hash;Meta(String n,long s,byte[] h){name=n;size=s;hash=h;}}private static final class Save{final Uri uri;final File file;final OutputStream out;Save(Uri u,File f,OutputStream o){uri=u;file=f;out=o;}}
}
