from pathlib import Path

p = Path('app/src/main/java/com/kenan/optishare/transfer/TransferService.java')
s = p.read_text()
old = '''        NotificationCompat.Builder builder = new NotificationCompat.Builder(this, CHANNEL)\n                .setSmallIcon(R.drawable.ic_optishare)\n                .setContentTitle(title)\n                .setContentText(text)\n                .setStyle(new NotificationCompat.BigTextStyle().bigText(text))\n                .setContentIntent(pending)\n                .setOnlyAlertOnce(true)\n                .setOngoing(ongoingProgress)\n                .addAction(0, "Cancel", stopPending);\n        if (ongoingProgress) builder.setProgress(100, progress, false);\n        return builder.build();'''
new = '''        NotificationCompat.Builder builder = new NotificationCompat.Builder(this, CHANNEL)\n                .setSmallIcon(R.drawable.ic_optishare)\n                .setContentTitle(title)\n                .setContentText(text)\n                .setStyle(new NotificationCompat.BigTextStyle().bigText(text))\n                .setContentIntent(pending)\n                .setOnlyAlertOnce(true)\n                .setOngoing(ongoingProgress);\n\n        if (ongoingProgress && activeManifest != null && activeItems != null) {\n            Intent pause = new Intent(this, TransferService.class).setAction(ACTION_PAUSE);\n            PendingIntent pausePending = PendingIntent.getService(this, 2, pause,\n                    PendingIntent.FLAG_UPDATE_CURRENT | immutable);\n            builder.addAction(0, "Pause", pausePending);\n        } else if (!ongoingProgress && "Transfer paused".equals(title)\n                && senderStore != null && senderStore.exists()) {\n            Intent resume = new Intent(this, TransferService.class).setAction(ACTION_RESUME_PENDING);\n            PendingIntent resumePending = PendingIntent.getService(this, 3, resume,\n                    PendingIntent.FLAG_UPDATE_CURRENT | immutable);\n            builder.addAction(0, "Resume", resumePending);\n        }\n        builder.addAction(0, "Cancel", stopPending);\n        if (ongoingProgress) builder.setProgress(100, progress, false);\n        return builder.build();'''
if s.count(old) != 1:
    raise SystemExit(f'notification anchor count={s.count(old)}')
p.write_text(s.replace(old, new, 1))
print('notification pause/resume controls applied')
